import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Category order follows the customer journey: learn what it is, install it,
 * connect it, read the data, then the AI layer, settings and API. Reference
 * material a customer consults rather than reads (guides, migration, privacy,
 * compliance, billing) sits after that, and support content closes.
 *
 * Order is fixed here and only here — a first-level `position` in a
 * `_category_.json` has no effect on these entries.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'implementation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reports & Insights',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reports',
        },
      ],
    },
    {
      type: 'category',
      label: 'LENS AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'lens',
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Analytics Prompts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'web-analytics-prompts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Settings',
      items: [
        {
          type: 'autogenerated',
          dirName: 'platform',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'GA4 Migration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ga4-migration',
        },
      ],
    },
    {
      type: 'category',
      label: 'Compare',
      items: [
        {
          type: 'autogenerated',
          dirName: 'compare',
        },
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        {
          type: 'autogenerated',
          dirName: 'use-cases',
        },
      ],
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: [
        {
          type: 'autogenerated',
          dirName: 'security-privacy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Compliance',
      items: [
        {
          type: 'autogenerated',
          dirName: 'compliance',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plans & Billing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'billing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        },
      ],
    },
  ],
};

export default sidebars;
