import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'First Steps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'first-steps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reports',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reports',
        },
      ],
    },
    {
      type: 'category',
      label: 'Metrics Insights',
      items: [
        {
          type: 'autogenerated',
          dirName: 'metrics-insights',
        },
      ],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'implementation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Privacy & Consentless Analytics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'privacy-and-consentless',
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      items: [
        {
          type: 'autogenerated',
          dirName: 'platform',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        {
          type: 'autogenerated',
          dirName: 'legal',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        },
      ],
    },
  ],
};

export default sidebars;